### ISSUE TITLE
How to make the face’s shadow proper

### ISSUE THREAD

**Issue by Rainbow-rose** [Manashiku/MMDGenshin#2]
I tried to use this shader but failed,the face‘s shadow could not move as the model moves, and it could only follow the global lighting.I tried the 0.1.3 and the 0.1.5,they all could not work properly.

**Comment by Manashiku** [comment]
We already talked about this on DeviantArt but I'll go ahead and respond here as well for anyone else facing an issue like this.

When you download and extract the shader, please check that your files have the proper encoding. You can do this by opening "Material.fxh" in a program like notepad++ and checking in the bottom right hand corner if it says Shift-JIS. If it isn't then you'll either need to redownload it from the release page or manually change and edit the bone name strings.
