### ISSUE TITLE
Post Rimlight normal Error

### ISSUE THREAD

**Issue by Elysia-simp** [Manashiku/MMDGenshin#3]
While it's correct if you use Post Rim in MMM, In MMD the shader uses ADDUV4 (Custom Normals) Rather than the models actual normals, Which causes errors for Genshin models that don't have ADDUV4 to have no Rim Light and if there is an ADDUV4 the Rim doesn't look right.

**Comment by Manashiku** [comment]
https://github.com/Manashiku/MMDGenshin/releases/tag/1.1.7
