### ISSUE TITLE
Black spots on fischl model even after troubleshooting/disabling effects

### ISSUE THREAD

**Issue by ziiaziia** [Manashiku/MMDGenshin#4]
After troubleshooting I'm pretty sure it's an issue with the mesh/transparent parts of her clothes, but I have no idea how to fix it. As you can see, after I apply the shading effects (I only changed the materials for her face and hair in PMXE, since I thought maybe changing the clothes materials was the problem) the transparent parts of her outfit are completely black (first image is before adding the shaders, second image is after).
![image](https://github.com/Manashiku/MMDGenshin/assets/142871999/a51d8466-b126-495f-831e-0e52d0a3a5db)
![image](https://github.com/Manashiku/MMDGenshin/assets/142871999/a9ed9300-9911-4916-b793-25daec7d777a)

Then, when I try to disable that specific effect subset, it inverts the effect so the skin on her body turns completely black.
![image](https://github.com/Manashiku/MMDGenshin/assets/142871999/b42a48c2-8bf9-4224-bf3b-cfda1d96e80d)

The same thing happens with the unedited Fischl model straight from aplaybox. Has this problem happened before, is there a solution?

**Comment by Yasuharaa** [comment]
It must be official model from bilibili/aplaybox site. Don't use their default texture that named in chinse.png just change with ripped texture like avatar_girl_..._body_diffuse.png (original)

**Comment by Manashiku** [comment]
This is a known problem and it's because of the way the model is set up to work for MMD's built in shader. As the shader is designed for datamined models, the only solution I can offer is tracking down the game exported files and porting the model yourself.
