### ISSUE TITLE
Outline Issue?

### ISSUE THREAD

**Issue by TheNameIs-M** [Manashiku/MMDGenshin#5]
I have been trying to figure this out for a while, and I am not sure if I am doing something wrong somewhere... The outlines for the model will not show up no matter what I do.

![image](https://github.com/Manashiku/MMDGenshin/assets/143708801/2311321e-f485-41b2-8623-9df33ad4cd83)
![image](https://github.com/Manashiku/MMDGenshin/assets/143708801/0960cc44-d422-43cc-9ab3-83e707843a70)

I tried changing the Outline Width to "100.0f" and even that did not make it show up. Keeping the outlines I had set from PMX Editor got overwritten by the shader as well, which I figure is the function, but I thought to try it anyway just to make sure.

I will mention that I am using the aplaybox models, since I know this code was meant for models ripped straight from the game. I don't have the know-how to do that, though, so...

Anyway, yeah. I'm not sure what I'm doing wrong. I really hope this gets seen ;-; I'm too nervous to contact anyone directly. I don't want to bother anyone. Especially if I am doing something completely and obviously wrong.

**Comment by Yasuharaa** [comment]
generate vertex color alpha using the plug-in (set vertex col alpha to 1.0). OR DON'T USE OFFICIAL/APLAYBOX MODEL, IT WON'T WORK PROPERLY WITH THIS SHADER (USE DATAMINED/RIP MODEL that comes with original vertex col).

**Comment by TheNameIs-M** [comment]
Ah, so I was replied to, but the comment is gone. Anyways, I apologize for being yet another user who is using an incompatible model (the aplaybox ones). You must get it often. ^^;

Well because I would like to have an answer for anyone looking at the same problem, the MMD Helper plug in for PMX Editor will make this work for the aplaybox models.

I had probably misread the step when setting up the model and thought it was only for if you are using MMM so I skipped it. It is the one about averaging normals to create edge lines.

Don't be freaked out by the edge lines around the eyes or mouth when the shader is loaded in, they just have to be rendered with different .fx files with outlines turned off. At least in my case, as without the shader and lightmaps, the parts look too bright on the model. The outline width line in the .fx works from there, so edit as needed!

**Comment by Yasuharaa** [comment]
Lol sorry my bad, I apogize. I hate aplaybox model.
So if you want the outlines, just use the helper plugin and generate vertex
color in 2nd UV.

Vertex color is the outline controller, so you have to set vertex color
alpha/ vertex color.w to 1.0f or 0.5 is fine. (Default 0.519)

**Comment by Yasuharaa** [comment]
For the face area, you have to manually painting the vertex color.
While painting set the vertex color.w to 0

**Comment by TheNameIs-M** [comment]
No worries, no worries. I had assumed many people have asked you about the
aplaybox models not working very well or easily despite it already being
said that the shader is meant for ripped models, so I can imagine that it
gets annoying. If it helps — and, of course, if you would be okay with it —
I might make a tutorial for the 1.1.6 version *for* those models since it
is still somewhat compatible, just more difficult, and I have seemed to
figure out how to apply it to them well enough. That way, there will be
less confusion for people asking about the aplaybox models and you won't
have to answer them repetitively

Thank you very much for answering even when it is probably very tiring and
annoying to.
