### ISSUE TITLE
The Metalic is different between v1.1.6 and v1.1.7

### ISSUE THREAD

**Issue by Yasuharaa** [Manashiku/MMDGenshin#6]
so I just realized after longtime using v1.1.6.
in v1.1.7 the metalic look is not good. (im using the same .fx files) but the result is different, v1.1.7 metalic are doff/no shiny

[![mmdgenshin-metalic-issue](https://github.com/Manashiku/MMDGenshin/assets/83198193/89a93222-6fc6-443b-8605-663ae66af6bd)](https://cdn.discordapp.com/attachments/1072695275677822996/1169771591463354479/mmdgenshin-metalic-issue.jpg?ex=65569db0&is=654428b0&hm=8dd4a98a4db6877492212794274ae9ab26015d97ee2ab16cee6aec6b56f854de&)

**Comment by Manashiku** [comment]
oh damn, thanks for letting me know. I'll look into what i might've messed up

**Comment by liyunxiang087** [comment]
> so I just realized after longtime using v1.1.6. in v1.1.7 the metalic look is not good. (im using the same .fx files) but the result is different, v1.1.7 metalic are doff/no shiny
> 
> [](https://cdn.discordapp.com/attachments/1072695275677822996/1169771591463354479/mmdgenshin-metalic-issue.jpg?ex=65569db0&is=654428b0&hm=8dd4a98a4db6877492212794274ae9ab26015d97ee2ab16cee6aec6b56f854de&)![mmdgenshin-metalic-issue](https://github.com/Manashiku/MMDGenshin/assets/83198193/89a93222-6fc6-443b-8605-663ae66af6bd)

**Comment by Manashiku** [comment]
Currently can't make a new release archive so for the time being download the metal.fxsub from the main repo here and replace the one the latest zip comes with it.

**Comment by Yasuharaa** [comment]
Hello I found the solve, Uncomment line 17 and 18 of metal.fxsub. Manashiku idk why you commented it//
// metal_sphere = saturate(metal_sphere * METAL_BRIGHTNESS);
// metal_sphere = saturate(metal_sphere); 
 to
metal_sphere = saturate(metal_sphere * METAL_BRIGHTNESS);
metal_sphere = saturate(metal_sphere);
