### ISSUE TITLE
Star Cloak

### ISSUE THREAD

**Issue by CKCFOGBJ** [Manashiku/MMDGenshin#7]
I'd like to ask, is it possible to replicate the star cloak of Paimon and Dainsleif in the 0.1.7 version of Genshin shader? If it is, how do I set the model? Because I added the cloak lightmap for Paimon as a sub-tex in PMX-editor but it doesn't seem to work

**Comment by Manashiku** [comment]
Paimon and Dainsleif's cloaks in game use a separate shader from that of the one regular characters use which is `miHoYo/Character/Base.shader`. In fact, while the two's cape shaders share code, they are technically different. Paimon uses the `miHoYo/Effects/Paimon_StarCloak.shader`. Dainsleif's is `miHoYo/Character/PaimonStarCloak.shader`. In my current dev version of this shader I do have code for these two implemented. I may end up enabling it in another later update but for the time being it isn't possible to replicate the shader with this current version of MMDGenshin.
