### ISSUE TITLE
Material Generator can't read JSON for 4.4 update

### ISSUE THREAD

**Issue by Yasuharaa** [Manashiku/MMDGenshin#8]
Does mhy changes their shader struct? it used "Key" instead of normal variable

![Screenshot 2023-12-24 195856](https://github.com/Manashiku/MMDGenshin/assets/83198193/a2095c4b-59f5-4fa6-b77c-54a5074a5aad)

**Comment by Manashiku** [comment]
This isn't a change done on mhy's end. The tool used to extract the models from the game recently was updated to change the output material jsons. I'll need to update the plugin to be able to read these new jsons. No idea though when I'll be able to get around to that, when i do update it i'll make a post on twitter.

**Comment by Yasuharaa** [comment]
AssetStudio has been fixed
https://crepe.moe/zUJgdSTj
![Screenshot 2024-01-02 200354](https://github.com/Manashiku/MMDGenshin/assets/83198193/7101484d-4cb0-487d-b258-86e0b3200b99)
